config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'blogs#index'
  get   'tweets'      =>  'blogs#index'     #ツイート一覧画面
  get   'tweets/new'  =>  'blogs#new'       #ツイート投稿画面
  post  'tweets'      =>  'blogs#create'    #ツイート投稿機能
  delete  'tweets/:id'  => 'blogs#destroy'  #ツイート削除機能
  get   'tweets/:id/edit'  => 'blogs#edit'  #ツイート編集機能
  patch   'tweets/:id'  => 'blogs#update'  #ツイート更新画面
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @tweets = Tweet.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @tweets = Tweet.new
 end

  def create
    Tweet.create(text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      Tweet.update(tweets_params)
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end

  def tweets_params
    params.permit(:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
  <div class="main-set">
<% @tweets.each do |tweet| %>
  <div class="card">
    <div class="card-hi">
    <p><%= simple_format(tweet.text) %></p>
    </div>
      <% if user_signed_in?%>
    <div class="card-row"></div>
     <li><%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %></li>
     <li><%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %></li>
          <% end %>
    </div>
     <% end %>
      <div class="card-row"></div>
        <%= paginate(@tweets) %>
    </div>
  </div>

app/views/blogs/create.html.erb
<a class="btn" href="/tweets">投稿一覧へ戻る</a>

app/views/blogs/destroy.html.erb
<a class="btn" href="/">投稿一覧へ戻る</a>

app/views/blogs/edit.html.erb
 <div class="contents row">
<%= form_for :tweet, url: tweets_path(@tweet) do |f| %>
    <h6>編集する</h6>
    <%= f.text_area :text, placeholder: "Text"%>
    <%= f.submit "SENT" %>
  <% end %>
</div>

app/views/blogs/index.html.erb
<div class="main">
  <%= render "blog"%>
</div>

app/views/blogs/new.html.erb
<div class="contents row">
  <%= form_for [@tweets] do |f| %>
    <h6>投稿する</h6>
    <%= f.text_area :text, placeholder: "Text"%>
    <%= f.submit "SENT" %>
  <% end %>
</div>

app/views/blogs/update.html.erb
<a class="btn" href="/">投稿一覧へ戻る</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogmini</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <style type="text/css" href="./blogs.scss"></style>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>         
  </head>
  <body>
<body>
  <nav class= "green accent-2">
    <div class="nav-wrapper">
    <a href="#" class="brand-logo">blog</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><a href="/tweets/new">NEW</a></li>
        <li><a data-method="delete" href="/users/sign_out">ログアウト</a></li>
      <% else %>
        <li><a href="/users/sign_in">ログイン</a></li>
        <li><a href="/users/sign_up">新規登録</a></li>
      <% end %>
      </ul>
    </div>
  </nav>
  <script type="text/javascript" src="./app.js"></script>
  <%= yield %>
</body>
</html>